// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repo

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	GetAllAccounts(ctx context.Context) ([]Account, error)
	GetAllEntries(ctx context.Context) ([]Entry, error)
	GetAllTransactions(ctx context.Context) ([]Transaction, error)
	GetUserFunds(ctx context.Context, accountID uuid.UUID) (int64, error)
}

var _ Querier = (*Queries)(nil)
